version: "3.8"

networks:
    ldmp:

services:
    postgresdb:
        build:
            context: ./config/db
            dockerfile: Dockerfile
        mem_limit: 512m
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        environment:
          - POSTGRES_DB=ldmpdb
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_PORT=5432
        networks:
            - ldmp
        env_file:
            - ./.env

    ldmpweb:
        build:
            context: ./app
        command: develop
        ports:
          - target: 9000
            published: 9000
            protocol: tcp
            mode: ingress
        volumes:
            - ./app:/home/app
            - static_volume:/home/app/static
            - staticfiles_volume:/home/app/staticfiles
        env_file:
            - ./.env
        depends_on:
            - postgresdb
        networks:
            - ldmp
          
volumes:
    static_volume:
    staticfiles_volume:
