# Generated by Django 3.2.8 on 2021-10-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='uid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
