# Generated by Django 3.2.8 on 2021-10-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_algorithm_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.algorithm'),
        ),
        migrations.DeleteModel(
            name='AlgorithmGroup',
        ),
    ]
