# Generated by Django 3.2.8 on 2021-10-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_algorithm_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.algorithm'),
        ),
    ]
