# Generated by Django 4.0a1 on 2021-10-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_algorithm_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
