# Generated by Django 4.0a1 on 2021-10-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aoi',
            name='country',
        ),
    ]
