# Generated by Django 4.0a1 on 2021-11-17 21:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_nation_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_es', models.CharField(blank=True, max_length=100, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('name_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
