# Generated by Django 4.0a1 on 2021-11-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='region_name',
        ),
    ]
