# Generated by Django 4.0a1 on 2021-11-18 15:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_aoi_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
