# Generated by Django 4.0a1 on 2021-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_aoi_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank='', default='', max_length=200, null=True),
        ),
    ]
