# Generated by Django 4.0a1 on 2021-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionscript',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
