# Generated by Django 4.0a1 on 2021-11-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_executionscript_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
