# Generated by Django 4.0a1 on 2021-11-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_algorithm_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
