# Generated by Django 4.0a1 on 2021-11-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_country_geom_alter_region_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
