# Generated by Django 4.0a1 on 2021-12-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_profile_photo_alter_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default='USER', max_length=50, null=True),
        ),
    ]
