# Generated by Django 4.0a1 on 2021-12-17 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0033_alter_settings_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Layer",
        ),
    ]
