# Generated by Django 4.0a1 on 2022-01-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionscript',
            name='run_mode',
        ),
    ]
