# Generated by Django 4.0a1 on 2022-01-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_executionscript_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionscript',
            name='parametrization_dialogue',
            field=models.TextField(default=None, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='scripts',
            field=models.ManyToManyField(to='account.ExecutionScript'),
        ),
        migrations.DeleteModel(
            name='Script',
        ),
    ]
