# Generated by Django 4.0a1 on 2022-01-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_executionscript_parametrization_dialogue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgorithmRunMode',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='item_type',
        ),
        migrations.DeleteModel(
            name='AlgorithmNodeType',
        ),
    ]
