# Generated by Django 4.0a1 on 2022-01-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_remove_script_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
