# Generated by Django 4.0a1 on 2022-01-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_matrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='date_created',
        ),
    ]
