# Generated by Django 4.0a1 on 2021-11-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationinputclass',
            name='name_long',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aggregationinputclass',
            name='name_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aggregationoutputclass',
            name='name_long',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aggregationoutputclass',
            name='name_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
