# Generated by Django 4.0a1 on 2021-10-21 14:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0007_remove_aoi_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField()),
                ('name', models.CharField(max_length=150)),
                ('no_data_value', models.FloatField(default=-32768.0)),
                ('activated', models.BooleanField(default=True)),
                ('add_to_map', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bands',
            },
        ),
        migrations.CreateModel(
            name='CloudResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data_path', models.CharField(max_length=150)),
                ('other_paths', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), size=None)),
                ('bands', models.ManyToManyField(to='job.Band')),
            ],
            options={
                'db_table': 'cloud_results',
            },
        ),
        migrations.CreateModel(
            name='LocalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_dir', models.CharField(max_length=150)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.aoi')),
            ],
            options={
                'db_table': 'local_contents',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('params', models.JSONField()),
            ],
            options={
                'db_table': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'job_results',
            },
        ),
        migrations.CreateModel(
            name='ScriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'script_statuses',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'job_statuses',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('md5_hash', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'urls',
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesTableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('table', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None), size=None)),
                ('jobresult_type', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='job.result')),
            ],
            options={
                'db_table': 'timeseries_tbl_results',
            },
        ),
        migrations.CreateModel(
            name='RemoteScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.scriptstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'remote_scripts',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('local_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.localcontext')),
                ('parameter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.parameters')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='LocalResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('data_path', models.CharField(max_length=200)),
                ('other_paths', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), size=None)),
                ('bands', models.ManyToManyField(to='job.Band')),
                ('jobresult_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='job.result')),
            ],
            options={
                'db_table': 'local_results',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('jobLocalResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.localresults')),
                ('jobcloudresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.cloudresults')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.parameters')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.executionscript')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.status')),
                ('timeseriestableresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.timeseriestableresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.AddField(
            model_name='cloudresults',
            name='jobresult_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.result'),
        ),
        migrations.AddField(
            model_name='cloudresults',
            name='urls',
            field=models.ManyToManyField(to='job.Url'),
        ),
    ]
