# Generated by Django 4.0a1 on 2021-10-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scriptstatus',
            table='script_status',
        ),
        migrations.AlterModelTable(
            name='status',
            table='job_status',
        ),
    ]
