# Generated by Django 4.0a1 on 2021-11-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_scriptstatus_table_alter_status_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobLocalResult',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobcloudresult',
        ),
        migrations.RemoveField(
            model_name='job',
            name='timeseriestableresult',
        ),
        migrations.AddField(
            model_name='job',
            name='results',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='job',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='params',
            field=models.TextField(),
        ),
    ]
