# Generated by Django 4.0a1 on 2021-11-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_params_alter_job_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='params',
        ),
    ]
