# Generated by Django 4.0a1 on 2021-11-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_job_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='params',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
