# Generated by Django 4.0a1 on 2021-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
