# Generated by Django 4.0a1 on 2021-12-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudresults',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='cloudresults',
            name='jobresult_type',
        ),
        migrations.RemoveField(
            model_name='cloudresults',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='localcontext',
            name='aoi',
        ),
        migrations.RemoveField(
            model_name='localresults',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='localresults',
            name='jobresult_type',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='local_context',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='remotescript',
            name='status',
        ),
        migrations.RemoveField(
            model_name='remotescript',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeseriestableresult',
            name='jobresult_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='params',
        ),
        migrations.RemoveField(
            model_name='job',
            name='results',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='CloudResults',
        ),
        migrations.DeleteModel(
            name='LocalContext',
        ),
        migrations.DeleteModel(
            name='LocalResults',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Parameters',
        ),
        migrations.DeleteModel(
            name='RemoteScript',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='TimeSeriesTableResult',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
