# Generated by Django 4.0a1 on 2021-12-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_job_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='task_notes',
            field=models.TextField(default=''),
        ),
    ]
