# Generated by Django 4.0a1 on 2021-12-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_job_task_name_job_task_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-start_date',)},
        ),
    ]
