# Generated by Django 4.0a1 on 2021-12-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_alter_layer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
