name: PEP8 Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    name: Lint
    steps:      
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: PEP8 Action
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
